import http from 'node:http';
import {championResult,archives,finalize,resetEvent,readArchive} from './local-event-management.mjs';
import { googleClient, validateGooglePayload } from './google-auth.mjs';
import { DatabaseSync } from 'node:sqlite';
import { randomBytes, createHash, timingSafeEqual } from 'node:crypto';
import { mkdirSync, readFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));
const data=process.env.DATA_DIR||path.join(root,'data');mkdirSync(data,{recursive:true});
const db=new DatabaseSync(path.join(data,'voting.sqlite'));
db.exec(`PRAGMA journal_mode=WAL; CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT); CREATE TABLE IF NOT EXISTS teams(id INTEGER PRIMARY KEY,group_id INTEGER,position INTEGER,name TEXT,song TEXT,members TEXT,photo TEXT); CREATE TABLE IF NOT EXISTS rounds(id INTEGER PRIMARY KEY,status TEXT DEFAULT 'ready',winner INTEGER); CREATE TABLE IF NOT EXISTS voters(hash TEXT PRIMARY KEY,name TEXT); CREATE TABLE IF NOT EXISTS votes(round INTEGER,voter TEXT,team INTEGER,PRIMARY KEY(round,voter)); CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,kind TEXT,identity TEXT,expires INTEGER);`);
db.exec("CREATE TABLE IF NOT EXISTS event_settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);CREATE TABLE IF NOT EXISTS event_archives(id TEXT PRIMARY KEY,created INTEGER NOT NULL,object_key TEXT NOT NULL)");
db.exec('CREATE TABLE IF NOT EXISTS google_voters(hash TEXT PRIMARY KEY,name TEXT,email TEXT)');
if(!db.prepare('SELECT id FROM teams LIMIT 1').get()){for(let g=0;g<3;g++)for(let p=1;p<=6;p++)db.prepare('INSERT INTO teams(group_id,position,name,song,members,photo) VALUES(?,?,?,?,?,?)').run(g,p,['草莓','檸檬','肉桂'][g]+'第'+p+'小組','待填歌曲','待填成員','');for(let i=1;i<=6;i++)db.prepare('INSERT INTO rounds(id) VALUES(?)').run(i);}
const adminPassword=process.env.ADMIN_PASSWORD||randomBytes(18).toString('base64url');
if(!process.env.ADMIN_PASSWORD)console.log('本次管理密碼：'+adminPassword+'（正式部署請設定 ADMIN_PASSWORD）');
const hash=s=>createHash('sha256').update(s).digest('hex');
const groups=['草莓','檸檬','肉桂'];
function state(admin=false){const teams=db.prepare('SELECT * FROM teams ORDER BY group_id,position').all();const rounds=db.prepare('SELECT * FROM rounds ORDER BY id').all().map(r=>({...r,teams:teams.filter(t=>t.position===r.id),counts:r.status==='settled'||admin?db.prepare('SELECT team,COUNT(*) count FROM votes WHERE round=? GROUP BY team').all(r.id):[]}));const totals=groups.map((name,g)=>({name,total:rounds.filter(r=>r.status==='settled'&&teams.find(t=>t.id===r.winner)?.group_id===g).reduce((n,r)=>n+(r.counts.find(c=>c.team===r.winner)?.count||0),0)}));if(admin)return {teams,rounds,totals,champion:championResult(db),archives:archives(db)};return {teams,rounds:rounds.map(r=>({...r,winner:null,counts:[]})),totals:[]};}
const fail=(message,status=400)=>{throw Object.assign(new Error(message),{status});};
const limit=new Map();function throttle(key,max){const now=Date.now();let a=(limit.get(key)||[]).filter(t=>now-t<60000);if(a.length>=max)fail('嘗試太頻繁，請稍後再試',429);a.push(now);limit.set(key,a);if(limit.size>10000)limit.clear();}
function session(req,kind='voter'){const cookieName=kind==='admin'?'admin_session':'voter_session';const token=new RegExp('(?:^|; )'+cookieName+'=([^;]+)').exec(req.headers.cookie||'')?.[1];const s=db.prepare('SELECT * FROM sessions WHERE token=? AND expires>?').get(token||'',Date.now());if(!s||(kind&&s.kind!==kind))fail('請先登入',401);return s;}
function login(res,kind,identity){const token=randomBytes(32).toString('hex');db.prepare('DELETE FROM sessions WHERE expires<?').run(Date.now());db.prepare('INSERT INTO sessions VALUES(?,?,?,?)').run(token,kind,identity,Date.now()+12*3600000);res.setHeader('Set-Cookie',`${kind==='admin'?'admin_session':'voter_session'}=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=43200${process.env.NODE_ENV==='production'?'; Secure':''}`);}
async function body(req){let chunks=[],size=0;for await(const c of req){size+=c.length;if(size>5*1024*1024)fail('檔案太大，請上傳小於 2MB 的照片',413);chunks.push(c);}try{return JSON.parse(Buffer.concat(chunks).toString()||'{}');}catch{fail('資料格式錯誤');}}
function text(s,max=300){if(typeof s!=='string'||!s.trim()||s.length>max)fail('請填寫有效資料');return s.trim();}
export const server=http.createServer(async(req,res)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy',process.env.NODE_ENV==='production'?'strict-origin-when-cross-origin':'no-referrer-when-downgrade');res.setHeader('Cross-Origin-Opener-Policy','same-origin-allow-popups');res.setHeader('Cache-Control','no-store');const url=new URL(req.url,'http://localhost');try{
if(url.pathname.startsWith('/api/')){res.setHeader('Content-Type','application/json; charset=utf-8');if(req.method==='POST'&&req.headers.origin&&req.headers.origin!==`${process.env.NODE_ENV==='production'?'https':'http'}://${req.headers.host}`)fail('來源不符',403);const b=req.method==='POST'?await body(req):{};let result={ok:true};
switch(url.pathname){
case '/api/state':result=state();break;

case '/api/me':{const s=session(req,'voter'),v=db.prepare('SELECT name,email FROM google_voters WHERE hash=?').get(s.identity);if(!v)fail('請重新登入',401);result={kind:'voter',name:v.name,email:v.email,votes:db.prepare('SELECT round,team FROM votes WHERE voter=?').all(s.identity)};break;}
case '/api/admin/me':{session(req,'admin');result={kind:'admin',name:'管理者'};break;}
case '/api/auth/config':result={clientId:process.env.GOOGLE_CLIENT_ID||''};break;
case '/api/auth/nonce':{if(req.method!=='POST')fail('方法不允許',405);throttle(req.socket.remoteAddress,20);const nonce=randomBytes(32).toString('hex');db.prepare('DELETE FROM sessions WHERE expires<?').run(Date.now());db.prepare('INSERT INTO sessions VALUES(?,?,?,?)').run(nonce,'nonce','',Date.now()+300000);res.setHeader('Set-Cookie',`google_nonce=${nonce}; HttpOnly; SameSite=Strict; Path=/; Max-Age=300${process.env.NODE_ENV==='production'?'; Secure':''}`);result={nonce};break;}
case '/api/auth/google':{if(req.method!=='POST')fail('方法不允許',405);throttle(req.socket.remoteAddress,20);if(!process.env.GOOGLE_CLIENT_ID)fail('Google 登入尚未啟用',503);const nonce=/(?:^|; )google_nonce=([^;]+)/.exec(req.headers.cookie||'')?.[1];if(!nonce||!db.prepare("SELECT 1 FROM sessions WHERE token=? AND kind='nonce' AND expires>?").get(nonce,Date.now()))fail('登入已逾時，請重新開啟登入視窗',401);let payload;try{const ticket=await googleClient.verifyIdToken({idToken:text(b.credential,12000),audience:process.env.GOOGLE_CLIENT_ID});payload=validateGooglePayload(ticket.getPayload(),process.env.GOOGLE_CLIENT_ID,nonce);}catch{fail('Gmail 驗證失敗，請使用有效的 Gmail 帳號重新登入',401);}db.prepare('DELETE FROM sessions WHERE token=?').run(nonce);const identity=hash('google:'+payload.sub);db.prepare('INSERT INTO google_voters VALUES(?,?,?) ON CONFLICT(hash) DO UPDATE SET name=excluded.name,email=excluded.email').run(identity,payload.name||payload.email,payload.email);login(res,'voter',identity);break;}
case '/api/admin/login':{if(req.method!=='POST')fail('方法不允許',405);throttle(req.socket.remoteAddress,10);const a=hash(String(b.password)),c=hash(adminPassword);if(!timingSafeEqual(Buffer.from(a),Buffer.from(c)))fail('管理密碼錯誤',401);login(res,'admin','admin');break;}
case '/api/logout':case '/api/admin/logout':{if(req.method!=='POST')fail('方法不允許',405);const kind=url.pathname==='/api/admin/logout'?'admin':'voter';const s=session(req,kind);db.prepare('DELETE FROM sessions WHERE token=?').run(s.token);res.setHeader('Set-Cookie',`${kind==='admin'?'admin_session':'voter_session'}=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0`);break;}
case '/api/vote':{if(req.method!=='POST')fail('方法不允許',405);const s=session(req,'voter');const r=db.prepare("SELECT * FROM rounds WHERE id=? AND status='open'").get(Number(b.round));if(!r)fail('此輪投票未開放');const t=db.prepare('SELECT * FROM teams WHERE id=? AND position=?').get(Number(b.team),r.id);if(!t)fail('此小組不在本輪');try{db.prepare('INSERT INTO votes VALUES(?,?,?)').run(r.id,s.identity,t.id);}catch{fail('你在這一輪已經投過票了',409);}break;}
default:{session(req,'admin');if(url.pathname.startsWith('/api/admin/archive/')){res.setHeader('Content-Disposition','attachment; filename="activity.json"');res.end(readArchive(db,data,url.pathname.split('/').pop()));return;}if(url.pathname==='/api/admin/reset'){if(req.method!=='POST')fail('方法不允許',405);result=resetEvent(db,data,b,()=>state(true));break;}if(url.pathname==='/api/admin/state'){result=state(true);break;}if(req.method!=='POST')fail('方法不允許',405);
if(url.pathname==='/api/admin/finalize'){result={champion:finalize(db,state(true))};}else if(url.pathname==='/api/admin/team'){const t=db.prepare('SELECT * FROM teams WHERE id=?').get(Number(b.id));if(!t)fail('小組不存在');if(db.prepare("SELECT 1 FROM rounds WHERE id=? AND status!='ready'").get(t.position))fail('本輪已開放或結算，不能修改');const photo=b.photo||'';if(photo&&!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(photo))fail('照片需為 PNG、JPEG 或 WebP');if(photo.length>2800000)fail('照片上限 2MB');db.prepare('UPDATE teams SET name=?,song=?,members=?,photo=? WHERE id=?').run(text(b.name,80),text(b.song,150),text(b.members,500),photo,t.id);}
else if(url.pathname==='/api/admin/order'){const ids=b.ids;if(!Array.isArray(ids)||ids.length!==6||new Set(ids).size!==6)fail('順序資料錯誤');const teams=ids.map(id=>db.prepare('SELECT * FROM teams WHERE id=?').get(Number(id)));if(teams.some(t=>!t)||new Set(teams.map(t=>t.group_id)).size!==1)fail('必須為同一大組');if(db.prepare("SELECT 1 FROM rounds WHERE status!='ready' LIMIT 1").get())fail('投票開始後不能改順序');db.exec('BEGIN');try{ids.forEach((id,i)=>db.prepare('UPDATE teams SET position=? WHERE id=?').run(i+1,id));db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}}
else if(url.pathname==='/api/admin/round'){const r=db.prepare('SELECT * FROM rounds WHERE id=?').get(Number(b.id));if(!r)fail('輪次不存在');if(b.action==='open'){if(r.status==='settled')fail('已結算不能再開放');db.exec("UPDATE rounds SET status='closed' WHERE status='open'");db.prepare("UPDATE rounds SET status='open' WHERE id=?").run(r.id);}else if(b.action==='close'){if(r.status!=='open')fail('本輪未開放');db.prepare("UPDATE rounds SET status='closed' WHERE id=?").run(r.id);}else if(b.action==='settle'){if(r.status==='ready'||r.status==='settled')fail('請先開放投票，且不能重複結算');const c=db.prepare('SELECT team,COUNT(*) count FROM votes WHERE round=? GROUP BY team ORDER BY count DESC').all(r.id);if(!c.length)fail('尚無票數，無法結算');const tied=c.filter(v=>v.count===c[0].count);let winner=tied[0].team;if(tied.length>1){db.prepare("UPDATE rounds SET status='closed' WHERE id=?").run(r.id);if(!tied.some(v=>v.team===Number(b.winner))) {result={tie:tied};break;}winner=Number(b.winner);}db.prepare("UPDATE rounds SET status='settled',winner=? WHERE id=?").run(winner,r.id);}else fail('操作不存在');}
else fail('找不到功能',404);}}
res.end(JSON.stringify(result));return;}
let filename=url.pathname==='/'?'index.html':url.pathname==='/admin'||url.pathname==='/admin/'||url.pathname==='/admin/performance'||url.pathname==='/admin/performance/'?'admin.html':decodeURIComponent(url.pathname).slice(1);const f=path.resolve(root,'public',filename);if(!f.startsWith(path.join(root,'public')+path.sep)||!existsSync(f))fail('找不到頁面',404);const ext=path.extname(f);res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.css':'text/css','.js':'text/javascript','.png':'image/png','.webp':'image/webp'})[ext]||'application/octet-stream');res.end(readFileSync(f));
}catch(e){res.statusCode=e.status||500;res.setHeader('Content-Type','application/json; charset=utf-8');res.end(JSON.stringify({error:e.status?e.message:'伺服器發生錯誤'}));if(!e.status)console.error(e);}});
if(process.argv[1]===fileURLToPath(import.meta.url))server.listen(Number(process.env.PORT)||3000,'0.0.0.0',()=>console.log('活色聲香 http://localhost:'+(process.env.PORT||3000)));


