// @ts-nocheck
import {env} from 'cloudflare:workers';
import {championResult,archives,isResetting,finalize,resetEvent,readArchive,clearArchives} from './event-management';
import {randomBytes,createHash,timingSafeEqual} from 'node:crypto';
import {jwtVerify,createRemoteJWKSet} from 'jose';
import {validateGooglePayload} from './google-validation';
const googleKeys=createRemoteJWKSet(new URL('https://www.googleapis.com/oauth2/v3/certs'));
const hash=s=>createHash('sha256').update(s).digest('hex');
const db={prepare(sql){return {get(...args){return env.DB.prepare(sql).bind(...args).first()},async all(...args){return (await env.DB.prepare(sql).bind(...args).all()).results},run(...args){return env.DB.prepare(sql).bind(...args).run()}}}};
async function seed(){const statements=[];for(let g=0;g<3;g++)for(let p=1;p<=6;p++)statements.push(env.DB.prepare('INSERT OR IGNORE INTO teams VALUES(?,?,?,?,?,?,?)').bind(g*6+p,g,p,groups[g]+'第'+p+'小組','待填歌曲','待填成員',''));for(let i=1;i<=6;i++)statements.push(env.DB.prepare('INSERT OR IGNORE INTO rounds(id) VALUES(?)').bind(i));await env.DB.batch(statements);}
const groups=['草莓','檸檬','肉桂'];
async function state(admin=false){const teams=await db.prepare('SELECT * FROM teams ORDER BY group_id,position').all();const rounds=await db.prepare('SELECT * FROM rounds ORDER BY id').all();for(const r of rounds){r.teams=teams.filter(t=>t.position===r.id);r.counts=r.status==='settled'||admin?await db.prepare('SELECT team,COUNT(*) count FROM votes WHERE round=? GROUP BY team').all(r.id):[];}const totals=groups.map((name,g)=>({name,total:rounds.filter(r=>r.status==='settled'&&teams.find(t=>t.id===r.winner)?.group_id===g).reduce((n,r)=>n+(r.counts.find(c=>c.team===r.winner)?.count||0),0)}));if(admin)return {teams,rounds,totals,champion:await championResult(),archives:await archives()};return {teams,rounds:rounds.map(r=>({...r,winner:null,counts:[]})),totals:[]};}
const fail=(message,status=400)=>{throw Object.assign(new Error(message),{status});};
async function throttle(key,max){key=String(key||'unknown')+':'+max;const now=Date.now();await db.prepare('INSERT INTO rate_limits VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN expires<? THEN 1 ELSE count+1 END,expires=CASE WHEN expires<? THEN excluded.expires ELSE expires END').run(key,now+60000,now,now);const row=await db.prepare('SELECT count FROM rate_limits WHERE key=?').get(key);if(row.count>max)fail('嘗試太頻繁，請稍後再試',429);}
async function session(req,kind='voter'){const cookieName=kind==='admin'?'admin_session':'voter_session';const token=new RegExp('(?:^|; )'+cookieName+'=([^;]+)').exec(req.headers.cookie||'')?.[1];const s=(await db.prepare('SELECT * FROM sessions WHERE token=? AND expires>?').get(token||'',Date.now()));if(!s||(kind&&s.kind!==kind))fail('請先登入',401);return s;}
async function login(res,kind,identity){const token=randomBytes(32).toString('hex');(await db.prepare('DELETE FROM sessions WHERE expires<?').run(Date.now()));(await db.prepare('INSERT INTO sessions VALUES(?,?,?,?)').run(token,kind,identity,Date.now()+12*3600000));res.setHeader('Set-Cookie',`${kind==='admin'?'admin_session':'voter_session'}=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=43200${'; Secure'}`);}
async function body(req){const raw=await req.native.text();if(new TextEncoder().encode(raw).length>5*1024*1024)fail('資料太大',413);try{return JSON.parse(raw||'{}');}catch{fail('資料格式錯誤');}}
function text(s,max=300){if(typeof s!=='string'||!s.trim()||s.length>max)fail('請填寫有效資料');return s.trim();}
export async function handle(native){const req={native,headers:{cookie:native.headers.get('cookie')||'',origin:native.headers.get('origin'),host:new URL(native.url).host},method:native.method,socket:{remoteAddress:native.headers.get('cf-connecting-ip')||'unknown'}};let output;const res={statusCode:200,headers:new Headers(),setHeader(k,v){this.headers.set(k,v)},end(v){output=new Response(v,{status:this.statusCode,headers:this.headers})}};await seed();const adminPassword=env.ADMIN_PASSWORD;if(!adminPassword)return Response.json({error:'管理密碼尚未設定'},{status:503});res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy',new URL(req.native.url).protocol==='https:'?'strict-origin-when-cross-origin':'no-referrer-when-downgrade');res.setHeader('Cross-Origin-Opener-Policy','same-origin-allow-popups');res.setHeader('Cache-Control','no-store');const url=new URL(native.url);try{
if(url.pathname.startsWith('/api/photo/')){const key=url.pathname.slice('/api/photo/'.length);if(!/^[a-f0-9]{48}$/.test(key))fail('照片不存在',404);const object=await env.BUCKET.get(key);if(!object)fail('照片不存在',404);const headers=new Headers();object.writeHttpMetadata(headers);headers.set('Cache-Control','public,max-age=86400');headers.set('X-Content-Type-Options','nosniff');return new Response(object.body,{headers});}
if(url.pathname.startsWith('/api/')){res.setHeader('Content-Type','application/json; charset=utf-8');if(req.method==='POST'&&req.headers.origin&&req.headers.origin!==`${new URL(req.native.url).protocol==='https:'?'https':'http'}://${req.headers.host}`)fail('來源不符',403);const b=req.method==='POST'?await body(req):{};let result={ok:true};
switch(url.pathname){
case '/api/state':if(await isResetting())fail('活動正在重設，請稍後再試',503);result=await state();break;

case '/api/me':{const s=await session(req,'voter'),v=(await db.prepare('SELECT name,email FROM google_voters WHERE hash=?').get(s.identity));if(!v)fail('請重新登入',401);result={kind:'voter',name:v.name,email:v.email,votes:(await db.prepare('SELECT round,team FROM votes WHERE voter=?').all(s.identity))};break;}
case '/api/admin/me':{await session(req,'admin');result={kind:'admin',name:'管理者'};break;}
case '/api/auth/config':result={clientId:env.GOOGLE_CLIENT_ID||''};break;
case '/api/auth/nonce':{if(req.method!=='POST')fail('方法不允許',405);await throttle(req.socket.remoteAddress,20);const nonce=randomBytes(32).toString('hex');(await db.prepare('DELETE FROM sessions WHERE expires<?').run(Date.now()));(await db.prepare('INSERT INTO sessions VALUES(?,?,?,?)').run(nonce,'nonce','',Date.now()+300000));res.setHeader('Set-Cookie',`google_nonce=${nonce}; HttpOnly; SameSite=Strict; Path=/; Max-Age=300${new URL(req.native.url).protocol==='https:'?'; Secure':''}`);result={nonce};break;}
case '/api/auth/google':{if(req.method!=='POST')fail('方法不允許',405);await throttle(req.socket.remoteAddress,20);if(!env.GOOGLE_CLIENT_ID)fail('Google 登入尚未啟用',503);const nonce=/(?:^|; )google_nonce=([^;]+)/.exec(req.headers.cookie||'')?.[1];if(!nonce||!(await db.prepare("SELECT 1 FROM sessions WHERE token=? AND kind='nonce' AND expires>?").get(nonce,Date.now())))fail('登入已逾時，請重新開啟登入視窗',401);let payload;try{const {payload:verified}=await jwtVerify(text(b.credential,12000),googleKeys,{audience:env.GOOGLE_CLIENT_ID,issuer:['accounts.google.com','https://accounts.google.com'],algorithms:['RS256']});payload=validateGooglePayload(verified,env.GOOGLE_CLIENT_ID,nonce);}catch{fail('Gmail 驗證失敗，請使用有效的 Gmail 帳號重新登入',401);}const consumed=await db.prepare("DELETE FROM sessions WHERE token=? AND kind='nonce'").run(nonce);if(!consumed.meta.changes)fail('請重新登入',401);const identity=hash('google:'+payload.sub);(await db.prepare('INSERT INTO google_voters VALUES(?,?,?) ON CONFLICT(hash) DO UPDATE SET name=excluded.name,email=excluded.email').run(identity,payload.name||payload.email,payload.email));await login(res,'voter',identity);break;}
case '/api/admin/login':{if(req.method!=='POST')fail('方法不允許',405);await throttle(req.socket.remoteAddress,10);const a=hash(String(b.password)),c=hash(adminPassword);if(!timingSafeEqual(Buffer.from(a),Buffer.from(c)))fail('管理密碼錯誤',401);await login(res,'admin','admin');break;}
case '/api/logout':case '/api/admin/logout':{if(req.method!=='POST')fail('方法不允許',405);const kind=url.pathname==='/api/admin/logout'?'admin':'voter';const s=await session(req,kind);(await db.prepare('DELETE FROM sessions WHERE token=?').run(s.token));res.setHeader('Set-Cookie',`${kind==='admin'?'admin_session':'voter_session'}=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0`);break;}
case '/api/vote':{if(req.method!=='POST')fail('方法不允許',405);const s=await session(req,'voter');const r=(await db.prepare("SELECT * FROM rounds WHERE id=? AND status='open'").get(Number(b.round)));if(!r)fail('此輪投票未開放');const t=(await db.prepare('SELECT * FROM teams WHERE id=? AND position=?').get(Number(b.team),r.id));if(!t)fail('此小組不在本輪');try{const inserted=await db.prepare("INSERT INTO votes SELECT ?,?,? WHERE EXISTS(SELECT 1 FROM rounds WHERE id=? AND status='open') AND EXISTS(SELECT 1 FROM teams WHERE id=? AND position=?)").run(r.id,s.identity,t.id,r.id,t.id,r.id);if(!inserted.meta.changes)fail('本輪已關閉',400);}catch(e){if(e.status)throw e;fail('你在這一輪已經投過票了',409);}break;}
default:{await session(req,'admin');if(url.pathname==='/api/admin/archives/clear'){if(req.method!=='POST')fail('方法不允許',405);result=await clearArchives(b);break;}if(url.pathname.startsWith('/api/admin/archive/'))return await readArchive(url.pathname.split('/').pop());if(url.pathname==='/api/admin/reset'){if(req.method!=='POST')fail('方法不允許',405);result=await resetEvent(b,()=>state(true));break;}if(await isResetting())fail('活動正在重設，請稍後再試',503);if(url.pathname==='/api/admin/state'){result=await state(true);break;}if(req.method!=='POST')fail('方法不允許',405);
if(url.pathname==='/api/admin/finalize'){result={champion:await finalize(await state(true))};}
else if(url.pathname==='/api/admin/team'){const t=(await db.prepare('SELECT * FROM teams WHERE id=?').get(Number(b.id)));if(!t)fail('小組不存在');if((await db.prepare("SELECT 1 FROM rounds WHERE id=? AND status!='ready'").get(t.position)))fail('本輪已開放或結算，不能修改');let photo=b.photo||'';if(photo&&!photo.startsWith('/api/photo/')&&!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(photo))fail('照片需為 PNG、JPEG 或 WebP');if(photo.length>2800000)fail('照片上限 2MB');if(photo.startsWith('/api/photo/')&&photo!==t.photo)fail('照片來源不符');if(photo.startsWith('data:')){const [prefix,encoded]=photo.split(',');const bytes=Uint8Array.from(atob(encoded),c=>c.charCodeAt(0));if(bytes.length>2*1024*1024)fail('照片上限 2MB');const key=randomBytes(24).toString('hex');await env.BUCKET.put(key,bytes,{httpMetadata:{contentType:prefix.slice(5).split(';')[0]}});photo='/api/photo/'+key;}(await db.prepare('UPDATE teams SET name=?,song=?,members=?,photo=? WHERE id=?').run(text(b.name,80),text(b.song,150),text(b.members,500),photo,t.id));}
else if(url.pathname==='/api/admin/order'){const ids=b.ids;if(!Array.isArray(ids)||ids.length!==6||new Set(ids).size!==6)fail('順序資料錯誤');const teams=await Promise.all(ids.map(id=>db.prepare('SELECT * FROM teams WHERE id=?').get(Number(id))));if(teams.some(t=>!t)||new Set(teams.map(t=>t.group_id)).size!==1)fail('必須為同一大組');if((await db.prepare("SELECT 1 FROM rounds WHERE status!='ready' LIMIT 1").get()))fail('投票開始後不能改順序');await env.DB.batch(ids.map((id,i)=>env.DB.prepare('UPDATE teams SET position=? WHERE id=?').bind(i+1,id)));}
else if(url.pathname==='/api/admin/round'){const r=(await db.prepare('SELECT * FROM rounds WHERE id=?').get(Number(b.id)));if(!r)fail('輪次不存在');if(b.action==='open'){if(r.status==='settled')fail('已結算不能再開放');await env.DB.batch([env.DB.prepare("UPDATE rounds SET status='closed' WHERE status='open' AND EXISTS(SELECT 1 FROM rounds WHERE id=? AND status!='settled')").bind(r.id),env.DB.prepare("UPDATE rounds SET status='open' WHERE id=? AND status!='settled'").bind(r.id)]);}else if(b.action==='close'){if(r.status!=='open')fail('本輪未開放');(await db.prepare("UPDATE rounds SET status='closed' WHERE id=?").run(r.id));}else if(b.action==='settle'){if(r.status==='ready'||r.status==='settled')fail('請先開放投票，且不能重複結算');await db.prepare("UPDATE rounds SET status='closed' WHERE id=? AND status='open'").run(r.id);const c=(await db.prepare('SELECT team,COUNT(*) count FROM votes WHERE round=? GROUP BY team ORDER BY count DESC').all(r.id));if(!c.length)fail('尚無票數，無法結算');const tied=c.filter(v=>v.count===c[0].count);let winner=tied[0].team;if(tied.length>1){(await db.prepare("UPDATE rounds SET status='closed' WHERE id=?").run(r.id));if(!tied.some(v=>v.team===Number(b.winner))) {result={tie:tied};break;}winner=Number(b.winner);}(await db.prepare("UPDATE rounds SET status='settled',winner=? WHERE id=?").run(winner,r.id));}else fail('操作不存在');}
else fail('找不到功能',404);}}
res.end(JSON.stringify(result));return output;}
return new Response('Not found',{status:404});
}catch(e){res.statusCode=e.status||500;res.setHeader('Content-Type','application/json; charset=utf-8');res.end(JSON.stringify({error:e.status?e.message:'伺服器發生錯誤'}));if(!e.status)console.error(e);}return output;}
